# Generated by Django 5.0.6 on 2024-07-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_author_image_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
